# services/notificationapi/overlays/production/secret-env.yaml
# PRODUCTION secrets for NotificationApi
---
apiVersion: v1
kind: Secret
metadata:
  name: notificationapi-secret
type: Opaque
stringData:
  REDIS_PASSWORD: "Q8DiwQaH3RkGQAHa"
