# services/notificationapi/base/kustomization.yaml
# Base resources for NotificationAPI service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
