apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: javaapp-uat
resources:
- ../../base
- configmap-env.yaml
- secret-env.yaml
images:
- name: inventory-service
  newName: image-registry.openshift-image-registry.svc:5000/javaapp-dev/inventory-service
  newTag: v1.5.0
