# app-gitops/overlays/sit/patch-notificationapi.yaml
# SIT-specific: 2 replicas, moderate resources
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: notificationapi
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
