# services/notificationapi/overlays/dev/secret-env.yaml
# DEV secrets for NotificationApi
---
apiVersion: v1
kind: Secret
metadata:
  name: notificationapi-secret
type: Opaque
stringData:
  REDIS_PASSWORD: "LzCCjiGv0b0gphK7"
