apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
type: Opaque
stringData:
  POSTGRESQL_USER: "orderservice"
  POSTGRESQL_PASSWORD: "JavaApp2024SecurePass"
  POSTGRESQL_DATABASE: "orderservice"
  REDIS_PASSWORD: "JavaRedis2024Pass"
