# app-gitops/base/serviceaccount.yaml
# Service account for the SampleAPI application pods
# Per-env SA is created by Phase 1, but this ensures GitOps manages it too
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: javaapp-sa
  labels:
    app: sampleapi
