# services/sampleapi/overlays/dev/configmap-env.yaml
# DEV environment configuration for SampleApi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sampleapi-env
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  DATABASE_URL: "Server=postgresql.sampleapi-dev.svc;Database=sampleapi;Port=5432;Username=sampleapi"
  LOGGING__LOGLEVEL__DEFAULT: "Debug"
  LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE: "Information"
  FEATURE_SWAGGER_ENABLED: "true"
  CORS_ALLOWED_ORIGINS: "https://frontend-dev.apps.cluster-pmqwq.pmqwq.sandbox270.opentlc.com"
  WeatherForecast__Location: "DEV"
  WeatherForecast__ForecastDays: "7"
  REDIS_URL: "redis.sampleapi-dev.svc:6379"
  NOTIFICATION_API_URL: "http://notificationapi.sampleapi-dev.svc:8081"
  EF_MIGRATE_ON_STARTUP: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-collector.openshift-tempo.svc:4317"
  OTEL_SERVICE_NAME: "sampleapi"
  OTEL_LOG_LEVEL: "debug"
  OTEL_DOTNET_AUTO_LOG_DIRECTORY: "/tmp"
