# services/sampleapi/overlays/dev/kustomization.yaml
# DEV overlay for SampleAPI — 1 replica
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sampleapi-dev

resources:
- ../../base
- configmap-env.yaml
- secret-env.yaml

patches:
- path: patch-deployment.yaml

# Image tag — updated by updateGitOps.groovy via: kustomize edit set image
images:
- name: sampleapi
  newName: image-registry.openshift-image-registry.svc:5000/sampleapi-dev/sampleapi
  newTag: main-6a80fc2
