# services/sampleapi/overlays/dev/secret-env.yaml
# DEV secrets for SampleApi
---
apiVersion: v1
kind: Secret
metadata:
  name: sampleapi-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: "8PBxP1cBGhg5pdf68rT9"
  API_KEY: "aN6BUq4sEoj21kQcF95soaREC2bXqpQS"
  JWT_SECRET: "J9JEn2W3clnu5NoECWIWHdV3w4W5E8BpWhagFaWNkZM6s8ik"
  REDIS_PASSWORD: "LzCCjiGv0b0gphK7"
