# services/notificationapi/overlays/uat/secret-env.yaml
# UAT secrets for NotificationApi
---
apiVersion: v1
kind: Secret
metadata:
  name: notificationapi-secret
type: Opaque
stringData:
  REDIS_PASSWORD: "WAmnmgMC3vGb8Kur"
