apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: javaapp-prod
resources:
- ../../base
- configmap-env.yaml
- secret-env.yaml
images:
- name: order-service
  newName: image-registry.openshift-image-registry.svc:5000/javaapp-dev/order-service
  newTag: v1.6.0
