// src/main/java/com/devsecops/payment/model/Payment.java
// JPA entity representing a payment transaction in the "payments" table.
package com.devsecops.payment.model;

import jakarta.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Payment entity — maps to the "payments" PostgreSQL table.
 *
 * <p>Implements Serializable to support Redis JSON serialization via
 * GenericJackson2JsonRedisSerializer. All monetary amounts use BigDecimal
 * to avoid floating-point precision issues (critical for financial data).
 *
 * <p>Status lifecycle: PENDING -> APPROVED | DECLINED -> REFUNDED
 */
@Entity
@Table(name = "payments")
public class Payment implements Serializable {

    private static final long serialVersionUID = 1L;

    /** Primary key — auto-generated by PostgreSQL sequence */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Reference to the originating order (from OrderService or external system) */
    @Column(name = "order_id")
    private Long orderId;

    /** Customer name — used for fraud check rules and notification addressing */
    @Column(name = "customer_name", nullable = false)
    private String customerName;

    /**
     * Payment amount in BigDecimal for precision.
     * Scale of 2 with precision 19 supports amounts up to trillions with cents.
     */
    @Column(name = "amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    /**
     * Payment processing status.
     * Valid values: PENDING, APPROVED, DECLINED, REFUNDED
     */
    @Column(name = "status", nullable = false, length = 20)
    private String status;

    /**
     * Method of payment.
     * Valid values: CREDIT_CARD, DEBIT, BANK_TRANSFER
     */
    @Column(name = "payment_method", length = 30)
    private String paymentMethod;

    /** Unique transaction reference (UUID) for external tracking and idempotency */
    @Column(name = "transaction_ref", unique = true, nullable = false, length = 36)
    private String transactionRef;

    /** Timestamp when the payment was processed (approved/declined) */
    @Column(name = "processed_at")
    private LocalDateTime processedAt;

    /** Timestamp when the payment record was created */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Set createdAt automatically before first persist */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // --- Constructors ---

    public Payment() {
    }

    public Payment(Long orderId, String customerName, BigDecimal amount, String status,
                   String paymentMethod, String transactionRef) {
        this.orderId = orderId;
        this.customerName = customerName;
        this.amount = amount;
        this.status = status;
        this.paymentMethod = paymentMethod;
        this.transactionRef = transactionRef;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getTransactionRef() {
        return transactionRef;
    }

    public void setTransactionRef(String transactionRef) {
        this.transactionRef = transactionRef;
    }

    public LocalDateTime getProcessedAt() {
        return processedAt;
    }

    public void setProcessedAt(LocalDateTime processedAt) {
        this.processedAt = processedAt;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Payment{" +
                "id=" + id +
                ", orderId=" + orderId +
                ", customerName='" + customerName + '\'' +
                ", amount=" + amount +
                ", status='" + status + '\'' +
                ", paymentMethod='" + paymentMethod + '\'' +
                ", transactionRef='" + transactionRef + '\'' +
                ", processedAt=" + processedAt +
                ", createdAt=" + createdAt +
                '}';
    }
}
