# services/sampleapi/overlays/sit/secret-env.yaml
# SIT secrets for SampleApi
---
apiVersion: v1
kind: Secret
metadata:
  name: sampleapi-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: "TsXJMo4GhCOWboBnXCTR"
  API_KEY: "RIOtQ4I3qfHWkVAV1RvgQnlAiz1uQW37"
  JWT_SECRET: "zUFcZwxX3s3QEypfG8rW9LYXLjs7ci94lsOIincVtGJ7QxP6"
  REDIS_PASSWORD: "PB9GkoqoMlGx3PaE"
