# argocd/notificationapi-dev.yaml
# ArgoCD Application: NotificationAPI in DEV — auto-sync
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notificationapi-dev
  namespace: openshift-gitops
  labels:
    team: devsecops
    app: notificationapi
    environment: dev
spec:
  project: devsecops
  source:
    repoURL: "https://gitlab-devsecops-gitlab.apps.cluster-pmqwq.pmqwq.sandbox270.opentlc.com/devsecops/app-gitops.git"
    targetRevision: main
    path: services/notificationapi/overlays/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sampleapi-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
