# app-gitops/overlays/production/patch-postgresql.yaml
# PRODUCTION-specific: higher resources for PostgreSQL
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
