apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      serviceAccountName: javaapp-sa
      containers:
        - name: payment-service
          image: payment-service
          ports:
            - containerPort: 8082
              name: http
          envFrom:
            - configMapRef:
                name: payment-service-env
            - secretRef:
                name: payment-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 24
