// inventory-service/src/main/java/com/devsecops/inventory/model/Product.java
// JPA entity representing a product in the inventory system.
// Maps to the "products" table in PostgreSQL.
// Each product tracks its current stock level, price, and reorder threshold.
package com.devsecops.inventory.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Product entity - represents a product in the inventory catalog.
 *
 * Key business rules:
 * - Product name must be unique (used as the lookup key by other services)
 * - stockQuantity is decremented on reserve and incremented on restock
 * - reorderLevel triggers low-stock alerts when stockQuantity drops below it
 * - lastRestocked tracks the most recent restock operation
 */
@Entity
@Table(name = "products")
public class Product {

    /** Primary key - auto-generated by PostgreSQL sequence */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Product name - must be unique, used as lookup key by order-service */
    @Column(nullable = false, unique = true)
    private String name;

    /** Product description - free-text field for product details */
    @Column(length = 1000)
    private String description;

    /** Product category - used for grouping and reporting (e.g., "Electronics", "Clothing") */
    @Column
    private String category;

    /**
     * Current stock quantity - the available units in inventory.
     * This value is decremented by reserveStock and incremented by restockProduct.
     * When this drops below reorderLevel, the product appears in low-stock reports.
     */
    @Column(name = "stock_quantity", nullable = false)
    private int stockQuantity;

    /** Unit price of the product - stored as BigDecimal for financial precision */
    @Column(precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Reorder level threshold - when stockQuantity falls at or below this value,
     * the product is flagged as low-stock in inventory reports and stats.
     */
    @Column(name = "reorder_level")
    private int reorderLevel;

    /** Timestamp of the last restock operation - updated by restockProduct */
    @Column(name = "last_restocked")
    private LocalDateTime lastRestocked;

    /** Record creation timestamp - set automatically on persist */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA lifecycle callback - sets the creation timestamp before initial persist.
     * This ensures every product record has an accurate creation time without
     * requiring the caller to set it explicitly.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // --- Constructors ---

    /** Default constructor required by JPA */
    public Product() {
    }

    /**
     * Convenience constructor for creating a new product with essential fields.
     *
     * @param name          unique product name
     * @param description   product description
     * @param category      product category
     * @param stockQuantity initial stock quantity
     * @param price         unit price
     * @param reorderLevel  low-stock threshold
     */
    public Product(String name, String description, String category,
                   int stockQuantity, BigDecimal price, int reorderLevel) {
        this.name = name;
        this.description = description;
        this.category = category;
        this.stockQuantity = stockQuantity;
        this.price = price;
        this.reorderLevel = reorderLevel;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public int getStockQuantity() {
        return stockQuantity;
    }

    public void setStockQuantity(int stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public int getReorderLevel() {
        return reorderLevel;
    }

    public void setReorderLevel(int reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public LocalDateTime getLastRestocked() {
        return lastRestocked;
    }

    public void setLastRestocked(LocalDateTime lastRestocked) {
        this.lastRestocked = lastRestocked;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", category='" + category + '\'' +
                ", stockQuantity=" + stockQuantity +
                ", price=" + price +
                ", reorderLevel=" + reorderLevel +
                '}';
    }
}
