// inventory-service/src/main/java/com/devsecops/inventory/model/StockMovement.java
// JPA entity representing a stock movement (audit trail for inventory changes).
// Maps to the "stock_movements" table in PostgreSQL.
// Every stock change (reserve, restock, adjustment) creates a StockMovement record
// for full traceability and audit compliance.
package com.devsecops.inventory.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * StockMovement entity - records every change to product stock levels.
 *
 * Movement types:
 * - IN:      Stock added (restock from supplier)
 * - OUT:     Stock removed (fulfilled order shipment)
 * - RESERVE: Stock reserved for a pending order (not yet shipped)
 *
 * Each movement is linked to a Product via ManyToOne relationship,
 * creating a complete audit trail of inventory changes.
 */
@Entity
@Table(name = "stock_movements")
public class StockMovement {

    /** Primary key - auto-generated by PostgreSQL sequence */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Foreign key to the product - stored as a column for query flexibility.
     * This allows querying movements by productId without a JOIN when the
     * full Product entity is not needed.
     */
    @Column(name = "product_id", nullable = false, insertable = false, updatable = false)
    private Long productId;

    /**
     * ManyToOne relationship to Product entity.
     * LAZY fetch to avoid loading the full product when only movement data is needed.
     * The JoinColumn maps to the same product_id column as the productId field above.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * Type of stock movement: IN, OUT, or RESERVE.
     * - IN: increases stockQuantity (restock)
     * - OUT: decreases stockQuantity (shipment)
     * - RESERVE: decreases stockQuantity (order reservation)
     */
    @Column(name = "movement_type", nullable = false, length = 10)
    private String movementType;

    /** Number of units moved - always positive, direction determined by movementType */
    @Column(nullable = false)
    private int quantity;

    /** Human-readable reason for the movement (e.g., "Order #12345", "Supplier restock") */
    @Column(length = 500)
    private String reason;

    /** Timestamp when this movement was recorded */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA lifecycle callback - sets the creation timestamp before initial persist.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // --- Constructors ---

    /** Default constructor required by JPA */
    public StockMovement() {
    }

    /**
     * Convenience constructor for creating a new stock movement.
     *
     * @param product      the product being moved
     * @param movementType IN, OUT, or RESERVE
     * @param quantity     number of units (positive value)
     * @param reason       human-readable reason for the movement
     */
    public StockMovement(Product product, String movementType, int quantity, String reason) {
        this.product = product;
        this.movementType = movementType;
        this.quantity = quantity;
        this.reason = reason;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public String getMovementType() {
        return movementType;
    }

    public void setMovementType(String movementType) {
        this.movementType = movementType;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "StockMovement{" +
                "id=" + id +
                ", productId=" + productId +
                ", movementType='" + movementType + '\'' +
                ", quantity=" + quantity +
                ", reason='" + reason + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
