# services/sampleapi/overlays/uat/secret-env.yaml
# UAT secrets for SampleApi
---
apiVersion: v1
kind: Secret
metadata:
  name: sampleapi-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: "D7e2ixR0BbKrE5GqWPMq"
  API_KEY: "cu20TkResNIGonQaYU2TwsLvyYa8ptG5"
  JWT_SECRET: "MhlGHjcEQz9AsNU8w1H0by57eR3UlbvCOg9XiKjLK8jfECD7"
  REDIS_PASSWORD: "WAmnmgMC3vGb8Kur"
