apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-env
data:
  DATABASE_URL: "jdbc:postgresql://postgresql.javaapp-uat.svc:5432/orderservice"
  DATABASE_USER: "orderservice"
  REDIS_HOST: "redis.javaapp-uat.svc"
  REDIS_PORT: "6379"
  SERVER_PORT: "8082"
  NOTIFICATIONAPI_URL: "http://notificationapi.sampleapi-uat.svc:8081"
  OTEL_SERVICE_NAME: "payment-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-collector.openshift-tempo.svc:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=javaapp-uat,deployment.environment=uat"
  SPRING_PROFILES_ACTIVE: "uat"
